### ISSUE TITLE
Documentation - awscli: An error occurred (SignatureDoesNotMatch) 

### ISSUE THREAD

**Issue by dhekimian** [scality/Zenko#10]
When following the Testing Steps at https://github.com/scality/Zenko/blob/master/swarm-testing/README.md I continued to run into `(SignatureDoesNotMatch)` with `:80` in the URL. 

```
$ aws --endpoint-url=http://localhost:80 s3 mb s3://test
make_bucket failed: s3://test An error occurred (SignatureDoesNotMatch) when calling the CreateBucket operation: The request signature we calculated does not match the signature you provided.

$ aws --endpoint-url=http://localhost s3 mb s3://test
make_bucket: test
```

Removing `:80` resolved my issue.

**Comment by RachedBenMustapha** [comment]
Thanks @dhekimian, we are updating the documentation.

**Comment by baslking** [comment]
Doc still not up to date can we do this soon?

**Comment by LaureVergeron** [comment]
Hi @baslking ,
On both the swarm-production and swarm-testing folders, this has been updated... Can you please tell me which tutorial you're talking about so I update it?
Cheers!

**Comment by baslking** [comment]
non-causal interaction it's fixed now

**Comment by LaureVergeron** [comment]
Closing since fixed then :)
