### ISSUE TITLE
Move charts/backbeat/templates/producer and consumer into templates/replication

### ISSUE THREAD

**Issue by vrancurel** [scality/Zenko#105]
We will have a clean

charts/backbeat/templates/api/
charts/backbeat/templates/replication/ (with producer and consumer)
charts/backbeat/templates/lifecycle/ (with producer and consumer)
etc

**Comment by rahulreddy** [comment]
👍

**Comment by ssalaues** [comment]
Closing issue. Addressed in PR #106 and merged.
