### ISSUE TITLE
Move down consumer and producer down one level in Values.yaml

### ISSUE THREAD

**Issue by vrancurel** [scality/Zenko#107]
Those 2 shall be in a sublevel "replication"

https://github.com/scality/Zenko/blob/master/charts/backbeat/values.yaml#L34
https://github.com/scality/Zenko/blob/master/charts/backbeat/values.yaml#L42

and need to change the templates accordingly

Values.replication.consumer.xxx

Because all backbeat services, lifecycle etc have producers and consu,ers

**Comment by giacomoguiulfo** [comment]
Closing issue. PR #109 was merged.
