### ISSUE TITLE
Redis-HA new chart location

### ISSUE THREAD

**Issue by pierluigilenoci** [scality/Zenko#1077]
Hi,
I'm asking here to understood if there is a plan to migrate the Redis-HA chart from stable to somewhere? Ref: https://github.com/helm/charts/issues/21103

**Comment by pierluigilenoci** [comment]
I found this. https://github.com/DandyDeveloper/charts/tree/master/charts/redis-ha 
Is it to be considered the definitive home of the chart?

**Comment by rahulreddy** [comment]
@pierluigilenoci Sorry this chart is not maintained anymore. Looks like you got a replacement https://github.com/helm/charts/issues/21103#issuecomment-732739086
