### ISSUE TITLE
Zenko Docker Swarm Testing installation reference link broken

### ISSUE THREAD

**Issue by emallinger** [scality/Zenko#1128]
Hello,
### Description
Link for Zenko Docker Swarm Testing installation gives 404 errorg.

### Steps to Reproduce the Issue

From the landing page check README and click on Zenko Docker Swarm Testing https://github.com/scality/Zenko/blob/development/2.0/swarm-testing

### Actual Results

404

### Expected Results

Open the page for installation instructions

Thanks,
Ema

**Comment by rahulreddy** [comment]
Hi @emallinger 
Thank you for pointing the error. We switched to using Kubernetes full time and Docker Swarm install is not maintained anymore. It will removed very soon.
Are you trying to install Zenko with Swarm?

**Comment by emallinger** [comment]
Hello,

I was hoping to try it, as I am more at ease with swarm than with
kubernetes.
I'll switch to kubernetes instead (that link is dead too by the way).
Thanks,
Ema

Le mer. 3 févr. 2021 à 17:23, Rahul Padigela <notifications@github.com> a
écrit :

**Comment by rahulreddy** [comment]
Closing as it has been addressed  by #1150
