### ISSUE TITLE
permanent port forwarding

### ISSUE THREAD

**Issue by samuellugassy** [scality/Zenko#117]
Hi can we have a permanent port forwarding in order to avoid typing the following command each time ?
kubectl port-forward zenko-cloudserver-front-6b869f97cd-r75nx 8000

**Comment by ssalaues** [comment]
If you are using the ingress options when deploying then you should be able to access via the specified hosts.

For example if you deploy (or helm upgrade your existing Zenko) with options similar to
```
$ helm install --name zenko \
          --set ingress.enabled=true \
          --set ingress.hosts[0]=zenko.local  \
          --set cloudserver-front.endpoint=zenko.local \
    zenko
```
Then you would be able to access the cloudserver service via endpoint `http://zenko.local`  with no port-forward required.
(Assuming that you have zenko.local set to resolve to your cluster either via /etc/hosts or DNS)
