### ISSUE TITLE
Docs should be in ReST format

### ISSUE THREAD

**Issue by smaffulli** [scality/Zenko#141]
As @ballot-scality mentioned in https://github.com/scality/Zenko/pull/137#pullrequestreview-130126368, markdown should not be used for authoring documentation.

There is currently a mix of formats, and the docs are scattered in multiple directories, too:

./charts/README.md
./charts/minikube.md
./charts/gke.md
./docs/orbit_registration.md
./swarm-testing/README.md
./swarm-production/README.md
./README.md

./docs/swarm_production_link.rst
./docs/index.rst
./tests/README.rst

**Comment by NicolasT** [comment]
Cfr. #146

**Comment by smaffulli** [comment]
We need to raise the priority of this issue and target it for 1.0. The state of the docs as they are published on http://zenko.readthedocs.io/en/latest/ is pretty bad. Lots of documents are 404

**Comment by smaffulli** [comment]
I think that 290770d96b2fd732a0633b2fe99f8e354b6c7713 solves this
