### ISSUE TITLE
Instance does not create

### ISSUE THREAD

**Issue by samuellugassy** [scality/Zenko#169]
When I run Zenko in the sandbox, the instance never gets created, even though it says: "Your instance is currently being created and will be ready in a few seconds.":

<img width="1230" alt="screen shot 2018-07-02 at 16 12 22" src="https://user-images.githubusercontent.com/7849577/42169032-eee8fca6-7e12-11e8-9806-110282815fab.png">

**Comment by smaffulli** [comment]
Thanks for trying Zenko :) here was an issue with the cluster, it's being solved and the system is coming back online.
