### ISSUE TITLE
Tutorial instances don't match doc

### ISSUE THREAD

**Issue by baslking** [scality/Zenko#18]
The Nginx instance is not named as the tutorial documentation indicates, or maybe that's a Mac version thing?  In any case the docker-stack.yml file uses this docker not one named Nginx

ID                  NAME                MODE                REPLICAS            IMAGE                       PORTS
awuju96gnhho        zenko-testing_lb    replicated          1/1                 zenko/loadbalancer:latest   *:80->80/tcp
p3us1marp8hq        zenko-testing_s3    replicated          1/1                 scality/s3server:latest     *:0->8000/tcp

**Comment by LaureVergeron** [comment]
Fixed, thanks :)
