### ISSUE TITLE
Zenko v1 API KO ?

### ISSUE THREAD

**Issue by arkpoah** [scality/Zenko#1907]
Hello,

We use Zenko v1 and get errors in the `zenko-cloudserver-manager` pod :
```
{"name":"S3","time":1687768956746,"url":"https://push.api.zenko.io/api/v1/instance/3d22af7d-42a1-4e6a-b846-4329477b4ee8/ws","level":"info","message":"connecting to push server","hostname":"zenko-cloudserver-6fd97d548-7fx6t","pid":19}
{"name":"S3","time":1687768957130,"error":{},"errorMessage":"Unexpected server response: 200","level":"error","message":"error from push server connection","hostname":"zenko-cloudserver-6fd97d548-7fx6t","pid":19}
{"name":"S3","time":1687768957130,"level":"info","message":"disconnected from push server, reconnecting in 10s","hostname":"zenko-cloudserver-6fd97d548-7fx6t","pid":19}
{"name":"S3","time":1687769632811,"level":"info","message":"push server ws not using proxy","hostname":"zenko-cloudserver-manager-677868dcd8-tfj4h","pid":20}
{"name":"S3","time":1687769633206,"error":{},"errorMessage":"Unexpected server response: 200","level":"error","message":"error from push server connection","hostname":"zenko-cloudserver-manager-677868dcd8-tfj4h","pid":20}
{"name":"S3","time":1687769633206,"level":"info","message":"disconnected from push server, reconnecting in 10s","hostname":"zenko-cloudserver-manager-677868dcd8-tfj4h","pid":20}
{"name":"S3","time":1687769643207,"url":"https://push.api.zenko.io/api/v1/instance/3d22af7d-42a1-4e6a-b846-4329477b4ee8/ws","level":"info","message":"connecting to push server","hostname":"zenko-cloudserver-manager-677868dcd8-tfj4h","pid":20}
{"name":"S3","time":1687769643207,"level":"info","message":"push server ws not using proxy","hostname":"zenko-cloudserver-manager-677868dcd8-tfj4h","pid":20}
{"name":"S3","time":1687769643589,"error":{},"errorMessage":"Unexpected server response: 200","level":"error","message":"error from push server connection","hostname":"zenko-cloudserver-manager-677868dcd8-tfj4h","pid":20}
{"name":"S3","time":1687769643590,"level":"info","message":"disconnected from push server, reconnecting in 10s","hostname":"zenko-cloudserver-manager-677868dcd8-tfj4h","pid":20}
```
Orbit UI is also not accessible, is there an incident on your side ?

Many of ours statics return randomly 403 errors.

Thanks

**Comment by rahulreddy** [comment]
Hello @arkpoah ,

I confirm that outage on Orbit UI, we are currently investigating it and will work on restoring as soon as root cause is found. The UI should not have an impact if you already have some existing workflows setup such as Replication to cloud.

**Comment by rahulreddy** [comment]
@arkpoah Orbit service is restored. Can you please check and confirm everything looks good on your end?

**Comment by arkpoah** [comment]
The main issue was the requests to the API which did not work, I confirm it works fine now.
It's also good for Orbit.
Thanks

**Comment by arkpoah** [comment]
Hello @rahulreddy ,
we still have the same issue, and Orbit is also no more accessible :
```
$ curl -I https://admin.zenko.io/user
HTTP/2 504 
server: awselb/2.0
date: Mon, 09 Oct 2023 19:35:58 GMT
content-type: text/html
content-length: 132
```

We get same error in cloudserver-manager logs : 
```
{"name":"S3","time":1696880444824,"level":"info","message":"push server ws not using proxy","hostname":"zenko-cloudserver-manager-677868dcd8-mnqz6","pid":20}
{"name":"S3","time":1696880455197,"error":{},"errorMessage":"Unexpected server response: 504","level":"error","message":"error from push server connection","hostname":"zenko-cloudserver-manager-677868dcd8-mnqz6","pid":20}
```

We get 403 http errors in cloudserver logs : 
`{"name":"S3","bucketName":"unicorn4ib-prod-v2","objectKey":"avatars/9c8e7cc8-65f5-4d6e-b543-527b5d77f9cd.png","bytesReceived":0,"bodyLength":0,"service":"s3","action":"GetObject","accessKey":"xxxxxxxxxxxx","bytesSent":232,"clientIP":"::ffff:10.200.1.15","clientPort":43912,"httpCode":403,"httpMethod":"GET","httpURL":"/unicorn4ib-prod-v2/avatars/9c8e7cc8-65f5-4d6e-b543-527b5d77f9cd.png?AWSAccessKeyId=xxxxxxxx&Expires=1696880867&Signature=fW2XX7qN%2FlSDYETH2Y5%2FWIG3Dw8%3D","contentLength":0,"time":1696879968656,"req_id":"bb6a9bc01e4ca73da756","elapsed_ms":4.985181,"level":"info","message":"responded with error XML","hostname":"zenko-cloudserver-5465847b55-6gcg5","pid":20}`

Thanks for help
