### ISSUE TITLE
Large zipfile upload never completes on Zenko from Cyberduck  Inbox x 

### ISSUE THREAD

**Issue by pspeciale** [scality/Zenko#25]
I started a new Zenko instance from Orbit - this works great.

First I verified the Zenko instance is accessible and accepts IO by uploading/downloading several smaller (< 1MB) files from Cyberduck, this succeeds.

I then tried to upload a 99MB zipfile.

The upload slows down from about 50MB/sec to under 5MB/sec, but does not stop at 99MB (100%), then continues  uploading the file again to 200% (198.4MB). The upload does not complete and the file never appears.

See the attachment. I tried it a few times and same behavior.

<img width="1086" alt="screen shot 2017-11-27 at 9 53 16 am" src="https://user-images.githubusercontent.com/13122589/33281849-82807592-d35b-11e7-9c81-54e08f6a7ad9.png">

**Comment by GiorgioRegni** [comment]
@RachedBenMustapha, can we consider that this one is solved now?

**Comment by pspeciale** [comment]
Yes, solved for now. The instructions you provided on throttling bandwidth is a sufficient solution

**Comment by GiorgioRegni** [comment]
Well, that sucks though, @RachedBenMustapha anything better?

**Comment by RachedBenMustapha** [comment]
I works in a lot more cases now and can be closed I think. We're still dependent on some timeouts that can happen for uploads that last for more than several minutes but it will be fixed when we move to the new sandbox tunneling architecture.

**Comment by GiorgioRegni** [comment]
OK, makes sense, I am closing then.
