### ISSUE TITLE
Zenko Orbit portal "Bucket" stats graph shows fractional values on vertical axis

### ISSUE THREAD

**Issue by pspeciale** [scality/Zenko#26]
Shows a scale from 0.0 to 1.0 "Buckets" in 0.1 increments, can this be fixed into whole units?

<img width="1252" alt="screen shot 2017-11-27 at 10 13 54 am" src="https://user-images.githubusercontent.com/13122589/33281955-dda69c1c-d35b-11e7-9250-1492b66b23ae.png">

**Comment by LaurenSpiegel** [comment]
did you notice that it's off by 1 bucket as well? 😃

**Comment by GiorgioRegni** [comment]
@RachedBenMustapha that's a fair comment, did you look at it?
