### ISSUE TITLE
node number, statefulset replicas, hardware failures

### ISSUE THREAD

**Issue by Zempashi** [scality/Zenko#399]
### Description

Please check node number configuration, it's a bit confusing to have in the same PR, someone talking about handling 2 failures, and also putting 3 replicas for software that require quorum
https://github.com/scality/Zenko/pull/152#discussion_r197957695

**Comment by ssalaues** [comment]
Thanks for pointing this out, I can definitely understand the confusion. The context of the conversation linked was whether or not the `offsets.topic.replication.factor` of 3 would be a safe value to keep or if it also needs the `nodeCount` for adequate resiliency. The point being made was that these should be safe values for both 3 and 5 node clusters which are the typical sizes we deploy.  I’ve updated the comment on the PR for anyone else in the future.

Also for clarification, the PR did not change the number of replicas for quorum but simply unified all the values that scale 1:1 with the node count through the use of the anchor value `nodeCount`. Other values like pod disruption budget still need manual configuration for larger than default cluster sizes.

However this brings up a really good point that we don’t have clear definitions of our fault tolerances (or lacking all together) at various node configurations in our docs. I’ve opened an issue for our tech writer to add this highly important, yet missing, information. 
https://github.com/scality/Zenko/blob/development/1.1/docs/Installation/Installation_Guide.rst
