### ISSUE TITLE
Release 1.1.6's main Chart.yaml is tagged 1.1.5

### ISSUE THREAD

**Issue by mastachand** [scality/Zenko#983]
The file Chart.yaml in kubernetes/zenko/ in the 1.1.6 tag/release is still tagging the 1.1.5 version. Hence when deployed, a helm list shows 1.1.5 while we have 1.1.6 deployed.

**Comment by rahulreddy** [comment]
Thanks @mastachand ! Let me fix and redo the chart. I think our release script did not update this as it should have.
