### ISSUE TITLE
jq error (redis.port)

### ISSUE THREAD

**Issue by jc-lab** [scality/Zenko#987]
Hello,
I installed zenko with helm (The symptoms are the same for both 1.1.6 and 1.2.0.)
```
$ helm install https://github.com/scality/Zenko/releases/download/1.2.0-rc.3/zenko-helm-chart-1.2.0-rc.3.tgz
```

But in some pods I get the following error:
```
jq: error: syntax error, unexpected ':', expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
. | .kafka.hosts="...-zenko-zenko-queue:9092" | .redis.port=tcp://10.244.153.77:6379 | .queuePopulator.logSource="mongo" | .queuePopulator.mongo.replicaSetHosts="...-zenko-mongodb-replicaset-0....-zenko-mongodb-replicaset:27017,zeronsoftn-local-zenko-mongodb-replicaset-1....-zenko-mongodb-replicaset:27017" | .s3.host="..." | .s3.port="80"                                                                            
jq: 1 compile error
```

Error in applying redis port in docker-entrypoint.sh.

Problem deployments are listed below:
* backbeat-gc-consumer
* backbeat-lifecycle-object-processor
* backbeat-lifecycle-conductor
* s3-data

I seem the below issue.
scality/cloudserver#1723

cloudstorage(s3-data) doesn't seem to have a problem with one replica, but backbeat has multiple replicas.
Is it ok to have redis on every pod, as in the above solution?

**Comment by rahulreddy** [comment]
@jc-lab Sorry this is coming a bit late, were you able to resolve this issue? I am curious which K8s and helm chart versions you are using.

**Comment by rahulreddy** [comment]
Sorry @jc-lab I am closing this issue as there is no response. Please reopen if you are facing the issue again.
